### ISSUE TITLE
Verify mobile functionality (QR payload)

### ISSUE THREAD

**Issue by 0xjjpa** [0xjjpa/onchecked#3]
**Background**
There's been a few transactions that were done using mobile wallets (the main use case for Onchecked). Yet, for some reason, they didn't triggered the "witnessed" event.

**Task Description**
- [x] Verify the payload on mobile is the same as in desktop
- [x] Patch any bug that might occur only on mobile wallets

**Comment by 0xjjpa** [comment]
See https://mumbai.polygonscan.com/tx/0xc6277afdee58eb1750364ba0d0d716e6cee0a8f9f86b5b6fa360b6946ed55a54, might not be on mobile wallets only.

**Comment by 0xjjpa** [comment]
Managed to get it to work with mobile with a new Metamask mobile wallet - https://mumbai.polygonscan.com/tx/0x1cb95af1341796d73993b1485eff235df18bb42864479da5794f361b4fd1614a

**Comment by 0xjjpa** [comment]
Can confirm that the payload is the same on mobile, and that the witnesssing works in two mobile wallets (see https://mumbai.polygonscan.com/tx/0xa8033e21cf0c348d3d4d92b049b0bfeb5082d680a83b35c53308cddf32369663#eventlog). The issue seems to be more when an existing wallet has already done some witnessing and tries to do it again. Confirming that use case.

**Comment by 0xjjpa** [comment]
Testing use case where `alice = wallet_1` and `bob = wallet_m`, then `wallet_1.sign(bh) = wallet_1_signed_bh`, `wallet_m.sign(wallet_1_signed_bh)`. This works.

Now, trying to see where `alice = wallet_2` and `bob = wallet_m`, so `wallet_2.sign(bh) = wallet_2_signed_bh`, `wallet_m.sign(wallet_2_signed_bh)`. This also works (https://mumbai.polygonscan.com/tx/0x82535a203bb741b364c8c28eac147107583c54e2d98f2ec17d5645c91f1da351)

Now, if you do `alice = wallet_m` and `bob = wallet_1`, so `wallet_m.sign(bh) = wallet_m_signed_bh` and `wallet_1.sign(wallet_m_signed_bh)`. This works, and even emits the `Attested` event - https://mumbai.polygonscan.com/tx/0xdf5cf7065ad59defa90effc0cbb3bc39a84d3820837468b4a19329e750c69294#eventlog

**Comment by 0xjjpa** [comment]
After careful analysis, can confirm the bug is due to https://github.com/0xjjpa/onchecked/blob/main/onchecked-contracts/contracts/PoE.sol#L73. In short, we do not do anything if an existing signature has already expired, and do not emit anything if that's the case. Thus, we need to cover for the following cases:

- [ ] User submits proof, but the proof took over >256 blocks to pass
- [ ] User submits proof, but the smart contract has already one stored and uses this one instead

We'll open a new issue for this.
