### ISSUE TITLE
[ UI ] Dashboard does not display the transaction or useful information

### ISSUE THREAD

**Issue by 0xjjpa** [0xjjpa/onchecked#4]
**Background**
Right now we only display the `signer` and `cosigner` information and that's it. Ideally, we should display information like a link to the transactiont that happened, the time when the witnessing occurred, etc.

**Task Description**
- [x] Add a link to the transaction hash
- [x] Add a subrow to display a row with the following information: Time of witnessing, blocks passed between signature + submit
- [ ] Include ENS to display names and avatars
